import type { ThemePalettes } from "../store/theme.models";

/**
 * Mirrors the exact mappings from Angular Material's
 * `core/tokens/m3/_md-sys-color.scss :: md-sys-color-values-light()`
 */
export function buildLightColorVariables(palettes: ThemePalettes): Record<string, string> {
  return {
    "background": palettes.neutral[98],
    "error": palettes.error[40],
    "error-container": palettes.error[90],
    "inverse-on-surface": palettes.neutral[95],
    "inverse-primary": palettes.primary[80],
    "inverse-surface": palettes.neutral[20],
    "on-background": palettes.neutral[10],
    "on-error": palettes.error[100],
    "on-error-container": palettes.error[30],
    "on-primary": palettes.primary[100],
    "on-primary-container": palettes.primary[30],
    "on-primary-fixed": palettes.primary[10],
    "on-primary-fixed-variant": palettes.primary[30],
    "on-secondary": palettes.secondary[100],
    "on-secondary-container": palettes.secondary[30],
    "on-secondary-fixed": palettes.secondary[10],
    "on-secondary-fixed-variant": palettes.secondary[30],
    "on-surface": palettes.neutral[10],
    "on-surface-variant": palettes.neutralVariant[30],
    "on-tertiary": palettes.tertiary[100],
    "on-tertiary-container": palettes.tertiary[30],
    "on-tertiary-fixed": palettes.tertiary[10],
    "on-tertiary-fixed-variant": palettes.tertiary[30],
    "outline": palettes.neutralVariant[50],
    "outline-variant": palettes.neutralVariant[80],
    "primary": palettes.primary[40],
    "primary-container": palettes.primary[90],
    "primary-fixed": palettes.primary[90],
    "primary-fixed-dim": palettes.primary[80],
    "scrim": palettes.neutral[0],
    "secondary": palettes.secondary[40],
    "secondary-container": palettes.secondary[90],
    "secondary-fixed": palettes.secondary[90],
    "secondary-fixed-dim": palettes.secondary[80],
    "shadow": palettes.neutral[0],
    "surface": palettes.neutral[98],
    "surface-bright": palettes.neutral[98],
    "surface-container": palettes.neutral[94],
    "surface-container-high": palettes.neutral[92],
    "surface-container-highest": palettes.neutral[90],
    "surface-container-low": palettes.neutral[96],
    "surface-container-lowest": palettes.neutral[100],
    "surface-dim": palettes.neutral[87],
    "surface-tint": palettes.primary[40],
    "surface-variant": palettes.neutralVariant[90],
    "tertiary": palettes.tertiary[40],
    "tertiary-container": palettes.tertiary[90],
    "tertiary-fixed": palettes.tertiary[90],
    "tertiary-fixed-dim": palettes.tertiary[80],
    "neutral10": palettes.neutral[10],
    "neutral-variant20": palettes.neutralVariant[20],
  };
}

/**
 * Mirrors the exact mappings from Angular Material's
 * `core/tokens/m3/_md-sys-color.scss :: md-sys-color-values-dark()`
 */
export function buildDarkColorVariables(palettes: ThemePalettes): Record<string, string> {
  return {
    "background": palettes.neutral[6],
    "error": palettes.error[80],
    "error-container": palettes.error[30],
    "inverse-on-surface": palettes.neutral[20],
    "inverse-primary": palettes.primary[40],
    "inverse-surface": palettes.neutral[90],
    "on-background": palettes.neutral[90],
    "on-error": palettes.error[20],
    "on-error-container": palettes.error[90],
    "on-primary": palettes.primary[20],
    "on-primary-container": palettes.primary[90],
    "on-primary-fixed": palettes.primary[10],
    "on-primary-fixed-variant": palettes.primary[30],
    "on-secondary": palettes.secondary[20],
    "on-secondary-container": palettes.secondary[90],
    "on-secondary-fixed": palettes.secondary[10],
    "on-secondary-fixed-variant": palettes.secondary[30],
    "on-surface": palettes.neutral[90],
    "on-surface-variant": palettes.neutralVariant[90],
    "on-tertiary": palettes.tertiary[20],
    "on-tertiary-container": palettes.tertiary[90],
    "on-tertiary-fixed": palettes.tertiary[10],
    "on-tertiary-fixed-variant": palettes.tertiary[30],
    "outline": palettes.neutralVariant[60],
    "outline-variant": palettes.neutralVariant[30],
    "primary": palettes.primary[80],
    "primary-container": palettes.primary[30],
    "primary-fixed": palettes.primary[90],
    "primary-fixed-dim": palettes.primary[80],
    "scrim": palettes.neutral[0],
    "secondary": palettes.secondary[80],
    "secondary-container": palettes.secondary[30],
    "secondary-fixed": palettes.secondary[90],
    "secondary-fixed-dim": palettes.secondary[80],
    "shadow": palettes.neutral[0],
    "surface": palettes.neutral[6],
    "surface-bright": palettes.neutral[24],
    "surface-container": palettes.neutral[12],
    "surface-container-high": palettes.neutral[17],
    "surface-container-highest": palettes.neutral[22],
    "surface-container-low": palettes.neutral[10],
    "surface-container-lowest": palettes.neutral[4],
    "surface-dim": palettes.neutral[6],
    "surface-tint": palettes.primary[80],
    "surface-variant": palettes.neutralVariant[30],
    "tertiary": palettes.tertiary[80],
    "tertiary-container": palettes.tertiary[30],
    "tertiary-fixed": palettes.tertiary[90],
    "tertiary-fixed-dim": palettes.tertiary[80],
    "neutral10": palettes.neutral[10],
    "neutral-variant20": palettes.neutralVariant[20],
  };
}
