import { Injectable } from "@angular/core";

import type { ThemeConfig, TonalPalette, ThemePalettes } from "../store/theme.models";

const EXPORT_TONES = [0, 4, 6, 10, 12, 17, 20, 22, 24, 25, 30, 35, 40, 50, 60, 70, 80, 87, 90, 92, 94, 95, 96, 98, 99, 100] as const;

@Injectable({ providedIn: "root" })
export class ScssExporterService {
  generateScss(config: ThemeConfig, palettes: ThemePalettes): string {
    const primaryPalette = this.#formatPalette(palettes.primary, "  ");
    const secondaryPalette = this.#formatPalette(palettes.secondary, "    ");
    const neutralPalette = this.#formatPalette(palettes.neutral, "    ");
    const neutralVariantPalette = this.#formatPalette(palettes.neutralVariant, "    ");
    const errorPalette = this.#formatPalette(palettes.error, "    ");
    const tertiaryPalette = this.#formatPalette(palettes.tertiary, "  ");

    return `@use "@angular/material" as mat;

// Generated by Angular Material Theme Builder

$my-palette: (
${primaryPalette}
  secondary: (
${secondaryPalette}
  ),
  neutral: (
${neutralPalette}
  ),
  neutral-variant: (
${neutralVariantPalette}
  ),
  error: (
${errorPalette}
  ),
);

$my-tertiary: (
${tertiaryPalette}
);

html {
  @include mat.theme(
    (
      color: (
        primary: $my-palette,
        tertiary: $my-tertiary,
        theme-type: ${config.themeType},
      ),
      typography: (
        brand-family: ${config.typography.brandFamily},
        plain-family: ${config.typography.plainFamily},
        bold-weight: ${config.typography.boldWeight},
        medium-weight: ${config.typography.mediumWeight},
        regular-weight: ${config.typography.regularWeight},
      ),
      density: ${config.density},
    )
  );
}
`;
  }

  #formatPalette(palette: TonalPalette, indent: string): string {
    return EXPORT_TONES.map((tone) => `${indent}${tone}: ${palette[tone]},`).join("\n");
  }
}
